package com.jtrent238.hammermod.items.materials;

import net.minecraftforge.common.util.EnumHelper;
import com.jtrent238.hammermod.Main;
import net.minecraft.item.Item;

public class HammerMaterial
{
    private static int emeraldMultiplier;
    private static int obsidianMultiplier;
    private static int eM;
    private static int oM;
    private static int nsM;
    private static int deM;
    private static int brM;
    private static int YT;
    private static int TWITCH;
    private static int PATREON;
    private static int mobM;
    private static int JSQ_Multiplier;
    private static int RAINBOW_MULTIPLIER;
    public static Item.ToolMaterial DEFAULT;
    public static Item.ToolMaterial WOOD;
    public static Item.ToolMaterial STONE;
    public static Item.ToolMaterial IRON;
    public static Item.ToolMaterial DIAMOND;
    public static Item.ToolMaterial GOLD;
    public static Item.ToolMaterial DIRT;
    public static Item.ToolMaterial GLASS;
    public static Item.ToolMaterial SAND;
    public static Item.ToolMaterial CACTUS;
    public static Item.ToolMaterial GRAVEL;
    public static Item.ToolMaterial EMERALD;
    public static Item.ToolMaterial GRASS;
    public static Item.ToolMaterial WOOL;
    public static Item.ToolMaterial OBSIDIAN;
    public static Item.ToolMaterial GLOWSTONE;
    public static Item.ToolMaterial REDSTONE;
    public static Item.ToolMaterial LAPIS;
    public static Item.ToolMaterial NETHERACK;
    public static Item.ToolMaterial SOULSAND;
    public static Item.ToolMaterial COAL;
    public static Item.ToolMaterial DRAGEGG;
    public static Item.ToolMaterial TNT;
    public static Item.ToolMaterial BEDROCK;
    public static Item.ToolMaterial CHARCOAL;
    public static Item.ToolMaterial ENDSTONE;
    public static Item.ToolMaterial GRANITE;
    public static Item.ToolMaterial ANDESITE;
    public static Item.ToolMaterial BONE;
    public static Item.ToolMaterial SPONGE;
    public static Item.ToolMaterial BRICK;
    public static Item.ToolMaterial SUGAR;
    public static Item.ToolMaterial SLIME;
    public static Item.ToolMaterial MELON;
    public static Item.ToolMaterial PUMPKIN;
    public static Item.ToolMaterial POTATO;
    public static Item.ToolMaterial CARROT;
    public static Item.ToolMaterial APPLE;
    public static Item.ToolMaterial ICE;
    public static Item.ToolMaterial PACKED_ICE;
    public static Item.ToolMaterial SNOW;
    public static Item.ToolMaterial CAKE;
    public static Item.ToolMaterial PURPUR;
    public static Item.ToolMaterial ENDBRICKS;
    public static Item.ToolMaterial CHORUS;
    public static Item.ToolMaterial URANIUM;
    public static Item.ToolMaterial TITANIUM;
    public static Item.ToolMaterial ADAM;
    public static Item.ToolMaterial CREEPER;
    public static Item.ToolMaterial PIG;
    public static Item.ToolMaterial COW;
    public static Item.ToolMaterial PAT;
    public static Item.ToolMaterial JEN;
    public static Item.ToolMaterial TDM;
    public static Item.ToolMaterial JSQ;
    public static Item.ToolMaterial SKY;
    public static Item.ToolMaterial TATTCKMC;
    public static Item.ToolMaterial MRGREG;
    public static Item.ToolMaterial MINEWORM;
    public static Item.ToolMaterial DAXEJ;
    public static Item.ToolMaterial INCAPGAMER;
    public static Item.ToolMaterial CRYOBBY;
    public static Item.ToolMaterial MYTHICAL;
    public static Item.ToolMaterial TOASTER;
    public static Item.ToolMaterial PUREDEVIL;
    public static Item.ToolMaterial LIGHTNING;
    public static Item.ToolMaterial RAINBOW;
    public static Item.ToolMaterial MISSINGTEX;
    
    static {
        HammerMaterial.emeraldMultiplier = 2;
        HammerMaterial.obsidianMultiplier = 2;
        HammerMaterial.eM = HammerMaterial.emeraldMultiplier;
        HammerMaterial.oM = HammerMaterial.obsidianMultiplier;
        HammerMaterial.nsM = HammerMaterial.eM + HammerMaterial.oM * 2;
        HammerMaterial.deM = HammerMaterial.nsM + HammerMaterial.eM + HammerMaterial.oM * 4;
        HammerMaterial.brM = HammerMaterial.nsM + HammerMaterial.eM + HammerMaterial.oM * HammerMaterial.deM;
        HammerMaterial.YT = 10;
        HammerMaterial.TWITCH = 10;
        HammerMaterial.PATREON = HammerMaterial.YT * HammerMaterial.TWITCH;
        HammerMaterial.mobM = 4;
        HammerMaterial.JSQ_Multiplier = 10;
        HammerMaterial.RAINBOW_MULTIPLIER = Main.numHammers;
        HammerMaterial.DEFAULT = EnumHelper.addToolMaterial("DEFAULT", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.WOOD = Item.ToolMaterial.WOOD;
        HammerMaterial.STONE = Item.ToolMaterial.STONE;
        HammerMaterial.IRON = Item.ToolMaterial.IRON;
        HammerMaterial.DIAMOND = Item.ToolMaterial.DIAMOND;
        HammerMaterial.GOLD = Item.ToolMaterial.GOLD;
        HammerMaterial.DIRT = EnumHelper.addToolMaterial("DIRT", 0, 10, 2.0f, 0.0f, 4);
        HammerMaterial.GLASS = EnumHelper.addToolMaterial("GLASS", 0, 6, 50.0f, 0.0f, 1);
        HammerMaterial.SAND = EnumHelper.addToolMaterial("SAND", 0, 6, 50.0f, 0.0f, 1);
        HammerMaterial.CACTUS = EnumHelper.addToolMaterial("CACTUS", 1, 32, 50.0f, 1.0f, 2);
        HammerMaterial.GRAVEL = EnumHelper.addToolMaterial("GRAVEL", 0, 6, 50.0f, 0.0f, 1);
        HammerMaterial.EMERALD = EnumHelper.addToolMaterial("EMERALD", 3 * HammerMaterial.eM, 1561 * HammerMaterial.eM, 8.0f * HammerMaterial.eM, 3.0f * HammerMaterial.eM, 10 * HammerMaterial.eM);
        HammerMaterial.GRASS = EnumHelper.addToolMaterial("GRASS", 0, 100, 60.0f, 0.0f, 2);
        HammerMaterial.WOOL = EnumHelper.addToolMaterial("WOOL", 0, 8, 50.0f, 0.0f, 1);
        HammerMaterial.OBSIDIAN = EnumHelper.addToolMaterial("OBSIDIAN", 3 * HammerMaterial.oM, 1561 * HammerMaterial.oM, 8.0f * HammerMaterial.oM, 3.0f * HammerMaterial.oM, 10 * HammerMaterial.oM);
        HammerMaterial.GLOWSTONE = EnumHelper.addToolMaterial("GLOWSTONE", 2, 84, 4.0f, 1.5f, 5);
        HammerMaterial.REDSTONE = EnumHelper.addToolMaterial("REDSTONE", 1, 150, 3.0f, 4.0f, 16);
        HammerMaterial.LAPIS = EnumHelper.addToolMaterial("LAPIS", 1, 125, 2.5f, 2.0f, 8);
        HammerMaterial.NETHERACK = EnumHelper.addToolMaterial("NETHERACK", 1, 400, 5.0f, 2.0f, 8);
        HammerMaterial.SOULSAND = EnumHelper.addToolMaterial("SOULSAND", 1, 60, 2.0f, 1.0f, 5);
        HammerMaterial.COAL = EnumHelper.addToolMaterial("COAL", 1, 450, 2.0f, 1.0f, 4);
        HammerMaterial.DRAGEGG = EnumHelper.addToolMaterial("DRAGEGG", 3 * HammerMaterial.deM, 1561 * HammerMaterial.deM, 8.0f * HammerMaterial.deM, 3.0f * HammerMaterial.deM, 10 * HammerMaterial.deM);
        HammerMaterial.TNT = EnumHelper.addToolMaterial("TNT", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.BEDROCK = EnumHelper.addToolMaterial("BEDROCK", 3 * HammerMaterial.brM, 1561 * HammerMaterial.brM, 8.0f * HammerMaterial.brM, 3.0f * HammerMaterial.brM, 10 * HammerMaterial.brM);
        HammerMaterial.CHARCOAL = EnumHelper.addToolMaterial("CHARCOAL", 1, 450, 2.0f, 1.0f, 4);
        HammerMaterial.ENDSTONE = Item.ToolMaterial.STONE;
        HammerMaterial.GRANITE = Item.ToolMaterial.STONE;
        HammerMaterial.ANDESITE = Item.ToolMaterial.STONE;
        HammerMaterial.BONE = EnumHelper.addToolMaterial("BONE", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.SPONGE = EnumHelper.addToolMaterial("SPONGE", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.BRICK = EnumHelper.addToolMaterial("BRICK", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.SUGAR = EnumHelper.addToolMaterial("SUGAR", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.SLIME = EnumHelper.addToolMaterial("SLIME", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.MELON = EnumHelper.addToolMaterial("MELON", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.PUMPKIN = EnumHelper.addToolMaterial("PUMPKIN", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.POTATO = EnumHelper.addToolMaterial("POTATO", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.CARROT = EnumHelper.addToolMaterial("CARROT", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.APPLE = EnumHelper.addToolMaterial("APPLE", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.ICE = EnumHelper.addToolMaterial("ICE", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.PACKED_ICE = EnumHelper.addToolMaterial("PACKED_ICE", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.SNOW = EnumHelper.addToolMaterial("SNOW", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.CAKE = EnumHelper.addToolMaterial("CAKE", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.PURPUR = EnumHelper.addToolMaterial("PURPUR", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.ENDBRICKS = EnumHelper.addToolMaterial("ENDBRICKS", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.CHORUS = EnumHelper.addToolMaterial("CHORUS", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.URANIUM = EnumHelper.addToolMaterial("URANIUM", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.TITANIUM = EnumHelper.addToolMaterial("TITANIUM", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.ADAM = EnumHelper.addToolMaterial("ADAM", 3, 1561, 8.0f, 3.0f, 10);
        HammerMaterial.CREEPER = EnumHelper.addToolMaterial("CREEPER", 3 * HammerMaterial.mobM, 1561 * HammerMaterial.mobM, 8.0f * HammerMaterial.mobM, 3.0f * HammerMaterial.mobM, 10 * HammerMaterial.mobM);
        HammerMaterial.PIG = EnumHelper.addToolMaterial("PIG", 3 * HammerMaterial.mobM, 1561 * HammerMaterial.mobM, 8.0f * HammerMaterial.mobM, 3.0f * HammerMaterial.mobM, 10 * HammerMaterial.mobM);
        HammerMaterial.COW = EnumHelper.addToolMaterial("COW", 3 * HammerMaterial.mobM, 1561 * HammerMaterial.mobM, 8.0f * HammerMaterial.mobM, 3.0f * HammerMaterial.mobM, 10 * HammerMaterial.mobM);
        HammerMaterial.PAT = EnumHelper.addToolMaterial("PAT", 3 * HammerMaterial.YT, 1561 * HammerMaterial.YT, 8.0f * HammerMaterial.YT, 3.0f * HammerMaterial.YT, 10 * HammerMaterial.YT);
        HammerMaterial.JEN = EnumHelper.addToolMaterial("JEN", 3 * HammerMaterial.YT, 1561 * HammerMaterial.YT, 8.0f * HammerMaterial.YT, 3.0f * HammerMaterial.YT, 10 * HammerMaterial.YT);
        HammerMaterial.TDM = EnumHelper.addToolMaterial("TDM", 3 * HammerMaterial.YT, 1561 * HammerMaterial.YT, 8.0f * HammerMaterial.YT, 3.0f * HammerMaterial.YT, 10 * HammerMaterial.YT);
        HammerMaterial.JSQ = EnumHelper.addToolMaterial("JSQ", 3 * HammerMaterial.YT + HammerMaterial.JSQ_Multiplier, 1561 * HammerMaterial.YT + HammerMaterial.JSQ_Multiplier, 8.0f * HammerMaterial.YT + HammerMaterial.JSQ_Multiplier, 3.0f * HammerMaterial.YT + HammerMaterial.JSQ_Multiplier, 10 * HammerMaterial.YT + HammerMaterial.JSQ_Multiplier);
        HammerMaterial.SKY = EnumHelper.addToolMaterial("SKY", 3 * HammerMaterial.YT, 1561 * HammerMaterial.YT, 8.0f * HammerMaterial.YT, 3.0f * HammerMaterial.YT, 10 * HammerMaterial.YT);
        HammerMaterial.TATTCKMC = EnumHelper.addToolMaterial("TATTCKMC", 3 * HammerMaterial.YT, 1561 * HammerMaterial.YT, 8.0f * HammerMaterial.YT, 3.0f * HammerMaterial.YT, 10 * HammerMaterial.YT);
        HammerMaterial.MRGREG = EnumHelper.addToolMaterial("MRGREG", 3 * HammerMaterial.YT, 1561 * HammerMaterial.YT, 8.0f * HammerMaterial.YT, 3.0f * HammerMaterial.YT, 10 * HammerMaterial.YT);
        HammerMaterial.MINEWORM = EnumHelper.addToolMaterial("MINEWORM", 3 * HammerMaterial.YT, 1561 * HammerMaterial.YT, 8.0f * HammerMaterial.YT, 3.0f * HammerMaterial.YT, 10 * HammerMaterial.YT);
        HammerMaterial.DAXEJ = EnumHelper.addToolMaterial("DAXEJ", 3 * HammerMaterial.TWITCH, 1561 * HammerMaterial.TWITCH, 8.0f * HammerMaterial.TWITCH, 3.0f * HammerMaterial.TWITCH, 10 * HammerMaterial.TWITCH);
        HammerMaterial.INCAPGAMER = EnumHelper.addToolMaterial("INCAPGAMER", 3 * HammerMaterial.TWITCH, 1561 * HammerMaterial.TWITCH, 8.0f * HammerMaterial.TWITCH, 3.0f * HammerMaterial.TWITCH, 10 * HammerMaterial.TWITCH);
        HammerMaterial.CRYOBBY = EnumHelper.addToolMaterial("CRYOBBY", 3, 8000, 6.0f, 6.0f, 10);
        HammerMaterial.MYTHICAL = EnumHelper.addToolMaterial("MYTHICAL", 3, 500, 10.0f, 15.0f, 5);
        HammerMaterial.TOASTER = EnumHelper.addToolMaterial("TOASTER", 1, 30000, 1000.0f, 0.5f, 10);
        HammerMaterial.PUREDEVIL = EnumHelper.addToolMaterial("PUREDEVIL", 3, 5000, 12.0f, 15.0f, 20);
        HammerMaterial.LIGHTNING = EnumHelper.addToolMaterial("LIGHTNING", 3, 2048, 6.0f, 5.0f, 10);
        HammerMaterial.RAINBOW = EnumHelper.addToolMaterial("RAINBOW", 3 * HammerMaterial.RAINBOW_MULTIPLIER, 1561 * HammerMaterial.RAINBOW_MULTIPLIER, 8.0f * HammerMaterial.RAINBOW_MULTIPLIER, 3.0f * HammerMaterial.RAINBOW_MULTIPLIER, 10 * HammerMaterial.RAINBOW_MULTIPLIER);
        HammerMaterial.MISSINGTEX = EnumHelper.addToolMaterial("MISSINGTEX", 3 * HammerMaterial.RAINBOW_MULTIPLIER / 2, 1561 * HammerMaterial.RAINBOW_MULTIPLIER / 2, 8.0f * HammerMaterial.RAINBOW_MULTIPLIER / 2.0f, 3.0f * HammerMaterial.RAINBOW_MULTIPLIER / 2.0f, 10 * HammerMaterial.RAINBOW_MULTIPLIER / 2);
    }
}
