package com.jtrent238.hammermod;

import net.minecraftforge.common.config.Configuration;
import org.apache.logging.log4j.Level;
import com.jtrent238.hammermod.proxy.CommonProxy;

public class Config
{
    private static final String CATEGORY_GENERAL = "general";
    private static final String CATEGORY_DEBUG = "debug";
    private static final String CATEGORY_CUSTOM_HAMMERS = "Custom Hammers";
    private static final String CATEGORY_SETTINGS = "Settings";
    private static final String CATEGORY_HAMMERS = "Hammers";
    public static boolean debugMode;
    public static boolean SMASH_BREAK_SOUND;
    public static boolean TOASTER_BREAK_SOUND;
    public static boolean RANDOM_TOAST;
    public static boolean SHARP_TOAST;
    public static boolean DEBUG_MODE;
    public static boolean RAINBOWCRAFT;
    public static boolean DISABLE_ALL_HAMMER;
    public static boolean TNT_HIT;
    public static boolean TNT_SPAWN;
    public static boolean WOOD_HAMMER_ENABLE;
    public static boolean STONE_HAMMER_ENABLE;
    public static boolean IRON_HAMMER_ENABLE;
    public static boolean GOLD_HAMMER_ENABLE;
    public static boolean DIAMOND_HAMMER_ENABLE;
    public static boolean DIRT_HAMMER_ENABLE;
    public static boolean GLASS_HAMMER_ENABLE;
    public static boolean SAND_HAMMER_ENABLE;
    public static boolean CACTUS_HAMMER_ENABLE;
    public static boolean GRAVEL_HAMMER_ENABLE;
    public static boolean WOOL_WHITE_HAMMER_ENABLE;
    public static boolean EMERALD_HAMMER_ENABLE;
    public static boolean GRASS_HAMMER_ENABLE;
    public static boolean OBISIDIAN_HAMMER_ENABLE;
    public static boolean GLOWSTONE_HAMMER_ENABLE;
    public static boolean REDSTONE_HAMMER_ENABLE;
    public static boolean LAPIZ_HAMMER_ENABLE;
    public static boolean NETHERRACK_HAMMER_ENABLE;
    public static boolean SOULSAND_HAMMER_ENABLE;
    public static boolean COAL_HAMMER_ENABLE;
    public static boolean CHARCOAL_HAMMER_ENABLE;
    public static boolean ENDSTONE_HAMMER_ENABLE;
    public static boolean BONE_HAMMER_ENABLE;
    public static boolean SPONGE_HAMMER_ENABLE;
    public static boolean BRICK_HAMMER_ENABLE;
    public static boolean SUGAR_HAMMER_ENABLE;
    public static boolean PUMPKIN_HAMMER_ENABLE;
    public static boolean POTATO_HAMMER_ENABLE;
    public static boolean CARROT_HAMMER_ENABLE;
    public static boolean APPLE_HAMMER_ENABLE;
    public static boolean ICE_HAMMER_ENABLE;
    public static boolean PACKEDICE_HAMMER_ENABLE;
    public static boolean CAKE_HAMMER_ENABLE;
    public static boolean DRAGONEGG_HAMMER_ENABLE;
    public static boolean TNT_HAMMER_ENABLE;
    public static boolean BEDROCK_HAMMER_ENABLE;
    public static boolean PIG_HAMMER_ENABLE;
    public static boolean COW_HAMMER_ENABLE;
    public static boolean CREEPER_HAMMER_ENABLE;
    public static boolean COPPER_HAMMER_ENABLE;
    public static boolean BRONZE_HAMMER_ENABLE;
    public static boolean SILVER_HAMMER_ENABLE;
    public static boolean TUNGSTEN_HAMMER_ENABLE;
    public static boolean RUBY_HAMMER_ENABLE;
    public static boolean TIN_HAMMER_ENABLE;
    public static boolean JADE_HAMMER_ENABLE;
    public static boolean AMETHEYST_HAMMER_ENABLE;
    public static boolean GRAPHITE_HAMMER_ENABLE;
    public static boolean CITRINE_HAMMER_ENABLE;
    public static boolean PIERRE_HAMMER_ENABLE;
    public static boolean ONYX_HAMMER_ENABLE;
    public static boolean NIKOLITE_HAMMER_ENABLE;
    public static boolean SILICA_HAMMER_ENABLE;
    public static boolean CINNABAR_HAMMER_ENABLE;
    public static boolean AMBER_HAMMER_ENABLE;
    public static boolean FERROUS_HAMMER_ENABLE;
    public static boolean ADAMITE_HAMMER_ENABLE;
    public static boolean SHINY_HAMMER_ENABLE;
    public static boolean XYCHORINUM_HAMMER_ENABLE;
    public static boolean URANIUM_HAMMER_ENABLE;
    public static boolean TITANIUM_HAMMER_ENABLE;
    public static boolean BLOODSTONE_HAMMER_ENABLE;
    public static boolean RUSTED_HAMMER_ENABLE;
    public static boolean ROSITE_HAMMER_ENABLE;
    public static boolean LIMONITE_HAMMER_ENABLE;
    public static boolean MITHRIL_HAMMER_ENABLE;
    public static boolean PROMETHEUM_HAMMER_ENABLE;
    public static boolean HEPATIZON_HAMMER_ENABLE;
    public static boolean POOP_HAMMER_ENABLE;
    public static boolean ANGMALLEN_HAMMER_ENABLE;
    public static boolean MAGANESE_HAMMER_ENABLE;
    public static boolean SEAREDBRICK_HAMMER_ENABLE;
    public static boolean ELECTRUM_HAMMER_ENABLE;
    public static boolean PIGIRON_HAMMER_ENABLE;
    public static boolean ARDITE_HAMMER_ENABLE;
    public static boolean ALUMITE_HAMMER_ENABLE;
    public static boolean COBALT_HAMMER_ENABLE;
    public static boolean OURCLASE_HAMMER_ENABLE;
    public static boolean HADEROTH_HAMMER_ENABLE;
    public static boolean INFUSCOILUM_HAMMER_ENABLE;
    public static boolean RUBBER_HAMMER_ENABLE;
    public static boolean DESICHALKOS_HAMMER_ENABLE;
    public static boolean MEUTOITE_HAMMER_ENABLE;
    public static boolean EXIMITE_HAMMER_ENABLE;
    public static boolean MIDASUM_HAMMER_ENABLE;
    public static boolean SANGUINITE_HAMMER_ENABLE;
    public static boolean INOLASHITE_HAMMER_ENABLE;
    public static boolean VULCANITE_HAMMER_ENABLE;
    public static boolean LEMURITE_HAMMER_ENABLE;
    public static boolean AMARDRINE_HAMMER_ENABLE;
    public static boolean CERUCLASE_HAMMER_ENABLE;
    public static boolean KALENDRIDE_HAMMER_ENABLE;
    public static boolean VYROXERS_HAMMER_ENABLE;
    public static boolean CARMOT_HAMMER_ENABLE;
    public static boolean TARTARITE_HAMMER_ENABLE;
    public static boolean ATLARUS_HAMMER_ENABLE;
    public static boolean ASTRAL_HAMMER_ENABLE;
    public static boolean CELENEGIL_HAMMER_ENABLE;
    public static boolean AREDRITE_HAMMER_ENABLE;
    public static boolean ORICALCUM_HAMMER_ENABLE;
    public static boolean TOASTER_HAMMER_ENABLE;
    public static boolean CRYOBBY_HAMMER_ENABLE;
    public static boolean TDM_HAMMER_ENABLE;
    public static boolean PAT_HAMMER_ENABLE;
    public static boolean JEN_HAMMER_ENABLE;
    public static boolean JSQ_HAMMER_ENABLE;
    public static boolean SKYRS_HAMMER_ENABLE;
    public static boolean MRGREGOR_HAMMER_ENABLE;
    public static boolean THACKATTACK_HAMMER_ENABLE;
    public static boolean DEEJAYAXEL_HAMMER_ENABLE;
    public static boolean INCAPABLEGAMER_HAMMER_ENABLE;
    public static boolean SLIME_HAMMER_ENABLE;
    public static boolean MELON_HAMMER_ENABLE;
    public static boolean SAPPHIRE_HAMMER_ENABLE;
    public static boolean MANYULLYN_HAMMER_ENABLE;
    public static boolean RAINBOW_HAMMER_ENABLE;
    public static boolean MISSING_TEXTURE_HAMMER_ENABLE;
    
    public static void readConfig() {
        final Configuration v0 = CommonProxy.config;
        try {
            /*SL:155*/v0.load();
            initGeneralConfig(/*EL:156*/v0);
        }
        catch (Exception v) {
            Main.logger.log(Level.ERROR, /*EL:158*/"Problem loading config file!", (Throwable)v);
        }
        finally {
            /*SL:160*/if (v0.hasChanged()) {
                /*SL:161*/v0.save();
            }
        }
    }
    
    private static void initGeneralConfig(final Configuration a1) {
        Config.SMASH_BREAK_SOUND = /*EL:184*/a1.get("Settings", "HammerCustomBreakSound", false).getBoolean(false);
        Config.TOASTER_BREAK_SOUND = /*EL:185*/a1.get("Settings", "ToasterCustomBreakSound", true).getBoolean(true);
        Config.RANDOM_TOAST = /*EL:186*/a1.get("Settings", "RandomToast", false).getBoolean(false);
        Config.SHARP_TOAST = /*EL:187*/a1.get("Settings", "SharpToast", false).getBoolean(false);
        Config.TNT_HIT = /*EL:188*/a1.get("Settings", "HitTNT", true).getBoolean(true);
        Config.TNT_SPAWN = /*EL:189*/a1.get("Settings", "SpawnTNT", false).getBoolean(false);
        Config.DEBUG_MODE = /*EL:190*/a1.get("Settings", "DebugMode", false).getBoolean(false);
        Config.RAINBOWCRAFT = /*EL:191*/a1.get("Settings", "RainbowHammerRecipe", false).getBoolean(false);
        Config.DISABLE_ALL_HAMMER = /*EL:192*/a1.get("Settings", "AllHammersDisabled", false).getBoolean(false);
        Config.WOOD_HAMMER_ENABLE = /*EL:196*/a1.get("Hammers", "Enable Wood Hammer", true).getBoolean(true);
        Config.STONE_HAMMER_ENABLE = /*EL:197*/a1.get("Hammers", "Enable Stone Hammer", true).getBoolean(true);
        Config.IRON_HAMMER_ENABLE = /*EL:198*/a1.get("Hammers", "Enable Iron Hammer", true).getBoolean(true);
        Config.GOLD_HAMMER_ENABLE = /*EL:199*/a1.get("Hammers", "Enable Gold Hammer", true).getBoolean(true);
        Config.DIAMOND_HAMMER_ENABLE = /*EL:200*/a1.get("Hammers", "Enable Diamond Hammer", true).getBoolean(true);
        Config.DIRT_HAMMER_ENABLE = /*EL:201*/a1.get("Hammers", "Enable Dirt Hammer", true).getBoolean(true);
        Config.GLASS_HAMMER_ENABLE = /*EL:202*/a1.get("Hammers", "Enable Glass Hammer", true).getBoolean(true);
        Config.SAND_HAMMER_ENABLE = /*EL:203*/a1.get("Hammers", "Enable Sand Hammer", true).getBoolean(true);
        Config.CACTUS_HAMMER_ENABLE = /*EL:204*/a1.get("Hammers", "Enable Cactus Hammer", true).getBoolean(true);
        Config.GRAVEL_HAMMER_ENABLE = /*EL:205*/a1.get("Hammers", "Enable Gravel Hammer", true).getBoolean(true);
        Config.WOOL_WHITE_HAMMER_ENABLE = /*EL:206*/a1.get("Hammers", "Enable Wool Hammer", true).getBoolean(true);
        Config.EMERALD_HAMMER_ENABLE = /*EL:207*/a1.get("Hammers", "Enable Emerald Hammer", true).getBoolean(true);
        Config.GRASS_HAMMER_ENABLE = /*EL:208*/a1.get("Hammers", "Enable Grass Hammer", true).getBoolean(true);
        Config.OBISIDIAN_HAMMER_ENABLE = /*EL:209*/a1.get("Hammers", "Enable Obisidan Hammer", true).getBoolean(true);
        Config.GLOWSTONE_HAMMER_ENABLE = /*EL:210*/a1.get("Hammers", "Enable Glowstone Hammer", true).getBoolean(true);
        Config.REDSTONE_HAMMER_ENABLE = /*EL:211*/a1.get("Hammers", "Enable Redstone Hammer", true).getBoolean(true);
        Config.LAPIZ_HAMMER_ENABLE = /*EL:212*/a1.get("Hammers", "Enable Lapiz Hammer", true).getBoolean(true);
        Config.NETHERRACK_HAMMER_ENABLE = /*EL:213*/a1.get("Hammers", "Enable Nethherack Hammer", true).getBoolean(true);
        Config.SOULSAND_HAMMER_ENABLE = /*EL:214*/a1.get("Hammers", "Enable SoulSand Hammer", true).getBoolean(true);
        Config.COAL_HAMMER_ENABLE = /*EL:215*/a1.get("Hammers", "Enable Coal Hammer", true).getBoolean(true);
        Config.CHARCOAL_HAMMER_ENABLE = /*EL:216*/a1.get("Hammers", "Enable Charcoal Hammer", true).getBoolean(true);
        Config.ENDSTONE_HAMMER_ENABLE = /*EL:217*/a1.get("Hammers", "Enable End Hammer", true).getBoolean(true);
        Config.BONE_HAMMER_ENABLE = /*EL:218*/a1.get("Hammers", "Enable Bone Hammer", true).getBoolean(true);
        Config.SPONGE_HAMMER_ENABLE = /*EL:219*/a1.get("Hammers", "Enable Sponge Hammer", true).getBoolean(true);
        Config.BRICK_HAMMER_ENABLE = /*EL:220*/a1.get("Hammers", "Enable Brick Hammer", true).getBoolean(true);
        Config.SUGAR_HAMMER_ENABLE = /*EL:221*/a1.get("Hammers", "Enable Sugar Hammer", true).getBoolean(true);
        Config.PUMPKIN_HAMMER_ENABLE = /*EL:222*/a1.get("Hammers", "Enable Pumpkin Hammer", true).getBoolean(true);
        Config.POTATO_HAMMER_ENABLE = /*EL:223*/a1.get("Hammers", "Enable Potato Hammer", true).getBoolean(true);
        Config.CARROT_HAMMER_ENABLE = /*EL:224*/a1.get("Hammers", "Enable Carrot Hammer", true).getBoolean(true);
        Config.APPLE_HAMMER_ENABLE = /*EL:225*/a1.get("Hammers", "Enable Apple Hammer", true).getBoolean(true);
        Config.ICE_HAMMER_ENABLE = /*EL:226*/a1.get("Hammers", "Enable Ice Hammer", true).getBoolean(true);
        Config.PACKEDICE_HAMMER_ENABLE = /*EL:227*/a1.get("Hammers", "Enable Packed Ice Hammer", true).getBoolean(true);
        Config.CAKE_HAMMER_ENABLE = /*EL:228*/a1.get("Hammers", "Enable Cake Hammer", true).getBoolean(true);
        Config.DRAGONEGG_HAMMER_ENABLE = /*EL:229*/a1.get("Hammers", "Enable Dragon Egg Hammer", true).getBoolean(true);
        Config.TNT_HAMMER_ENABLE = /*EL:230*/a1.get("Hammers", "Enable TNT Hammer", true).getBoolean(true);
        Config.BEDROCK_HAMMER_ENABLE = /*EL:231*/a1.get("Hammers", "Enable Bedrock Hammer", true).getBoolean(true);
        Config.SLIME_HAMMER_ENABLE = /*EL:232*/a1.get("Hammers", "Enable Slime Hammer", true).getBoolean(true);
        Config.MELON_HAMMER_ENABLE = /*EL:233*/a1.get("Hammers", "Enable Melon Hammer", true).getBoolean(true);
        Config.PIG_HAMMER_ENABLE = /*EL:237*/a1.get("Hammers", "Enable Pig Hammer", true).getBoolean(true);
        Config.COW_HAMMER_ENABLE = /*EL:238*/a1.get("Hammers", "Enable Cow Hammer", true).getBoolean(true);
        Config.CREEPER_HAMMER_ENABLE = /*EL:239*/a1.get("Hammers", "Enable Creeper Hammer", true).getBoolean(true);
        Config.COPPER_HAMMER_ENABLE = /*EL:243*/a1.get("Hammers", "Enable Copper Hammer", true).getBoolean(true);
        Config.BRONZE_HAMMER_ENABLE = /*EL:244*/a1.get("Hammers", "Enable Bronze Hammer", true).getBoolean(true);
        Config.SILVER_HAMMER_ENABLE = /*EL:245*/a1.get("Hammers", "Enable Silver Hammer", true).getBoolean(true);
        Config.TUNGSTEN_HAMMER_ENABLE = /*EL:246*/a1.get("Hammers", "Enable Tungsten Hammer", true).getBoolean(true);
        Config.RUBY_HAMMER_ENABLE = /*EL:247*/a1.get("Hammers", "Enable Ruby Hammer", true).getBoolean(true);
        Config.TIN_HAMMER_ENABLE = /*EL:248*/a1.get("Hammers", "Enable Tin Hammer", true).getBoolean(true);
        Config.JADE_HAMMER_ENABLE = /*EL:249*/a1.get("Hammers", "Enable Jade Hammer", true).getBoolean(true);
        Config.AMETHEYST_HAMMER_ENABLE = /*EL:250*/a1.get("Hammers", "Enable Ametheyst Hammer", true).getBoolean(true);
        Config.GRAPHITE_HAMMER_ENABLE = /*EL:251*/a1.get("Hammers", "Enable Graphite Hammer", true).getBoolean(true);
        Config.CITRINE_HAMMER_ENABLE = /*EL:252*/a1.get("Hammers", "Enable Citrine Hammer", true).getBoolean(true);
        Config.PIERRE_HAMMER_ENABLE = /*EL:253*/a1.get("Hammers", "Enable Pierre Hammer", true).getBoolean(true);
        Config.ONYX_HAMMER_ENABLE = /*EL:254*/a1.get("Hammers", "Enable Onyx Hammer", true).getBoolean(true);
        Config.NIKOLITE_HAMMER_ENABLE = /*EL:255*/a1.get("Hammers", "Enable Nikolite Hammer", true).getBoolean(true);
        Config.SILICA_HAMMER_ENABLE = /*EL:256*/a1.get("Hammers", "Enable Silica Hammer", true).getBoolean(true);
        Config.CINNABAR_HAMMER_ENABLE = /*EL:257*/a1.get("Hammers", "Enable Cinnabar Hammer", true).getBoolean(true);
        Config.AMBER_HAMMER_ENABLE = /*EL:258*/a1.get("Hammers", "Enable Amber Hammer", true).getBoolean(true);
        Config.FERROUS_HAMMER_ENABLE = /*EL:259*/a1.get("Hammers", "Enable Ferrous Hammer", true).getBoolean(true);
        Config.ADAMITE_HAMMER_ENABLE = /*EL:260*/a1.get("Hammers", "Enable Adamite Hammer", true).getBoolean(true);
        Config.SHINY_HAMMER_ENABLE = /*EL:261*/a1.get("Hammers", "Enable Shiny Hammer", true).getBoolean(true);
        Config.XYCHORINUM_HAMMER_ENABLE = /*EL:262*/a1.get("Hammers", "Enable Xychorinum Hammer", true).getBoolean(true);
        Config.URANIUM_HAMMER_ENABLE = /*EL:263*/a1.get("Hammers", "Enable Uranium Hammer", true).getBoolean(true);
        Config.TITANIUM_HAMMER_ENABLE = /*EL:264*/a1.get("Hammers", "Enable Titanium Hammer", true).getBoolean(true);
        Config.BLOODSTONE_HAMMER_ENABLE = /*EL:265*/a1.get("Hammers", "Enable Bloodstone Hammer", true).getBoolean(true);
        Config.RUSTED_HAMMER_ENABLE = /*EL:266*/a1.get("Hammers", "Enable Rusted Hammer", true).getBoolean(true);
        Config.ROSITE_HAMMER_ENABLE = /*EL:267*/a1.get("Hammers", "Enable Rosite Hammer", true).getBoolean(true);
        Config.LIMONITE_HAMMER_ENABLE = /*EL:268*/a1.get("Hammers", "Enable Limonite Hammer", true).getBoolean(true);
        Config.MITHRIL_HAMMER_ENABLE = /*EL:269*/a1.get("Hammers", "Enable Mithril Hammer", true).getBoolean(true);
        Config.PROMETHEUM_HAMMER_ENABLE = /*EL:270*/a1.get("Hammers", "Enable Prometheum Hammer", true).getBoolean(true);
        Config.HEPATIZON_HAMMER_ENABLE = /*EL:271*/a1.get("Hammers", "Enable Hepatizon Hammer", true).getBoolean(true);
        Config.POOP_HAMMER_ENABLE = /*EL:272*/a1.get("Hammers", "Enable Poop Hammer", true).getBoolean(true);
        Config.ANGMALLEN_HAMMER_ENABLE = /*EL:273*/a1.get("Hammers", "Enable Angmallen Hammer", true).getBoolean(true);
        Config.MAGANESE_HAMMER_ENABLE = /*EL:274*/a1.get("Hammers", "Enable Maganese Hammer", true).getBoolean(true);
        Config.SEAREDBRICK_HAMMER_ENABLE = /*EL:275*/a1.get("Hammers", "Enable SearedBrick Hammer", true).getBoolean(true);
        Config.ELECTRUM_HAMMER_ENABLE = /*EL:276*/a1.get("Hammers", "Enable Electrum Hammer", true).getBoolean(true);
        Config.PIGIRON_HAMMER_ENABLE = /*EL:277*/a1.get("Hammers", "Enable Pig Iron Hammer", true).getBoolean(true);
        Config.ARDITE_HAMMER_ENABLE = /*EL:278*/a1.get("Hammers", "Enable Ardite Hammer", true).getBoolean(true);
        Config.ALUMITE_HAMMER_ENABLE = /*EL:279*/a1.get("Hammers", "Enable Alumite Hammer", true).getBoolean(true);
        Config.COBALT_HAMMER_ENABLE = /*EL:280*/a1.get("Hammers", "Enable Cobalt Hammer", true).getBoolean(true);
        Config.OURCLASE_HAMMER_ENABLE = /*EL:281*/a1.get("Hammers", "Enable Ourclase Hammer", true).getBoolean(true);
        Config.HADEROTH_HAMMER_ENABLE = /*EL:282*/a1.get("Hammers", "Enable Haderoth Hammer", true).getBoolean(true);
        Config.INFUSCOILUM_HAMMER_ENABLE = /*EL:283*/a1.get("Hammers", "Enable Infuscoilum Hammer", true).getBoolean(true);
        Config.RUBBER_HAMMER_ENABLE = /*EL:284*/a1.get("Hammers", "Enable Rubber Hammer", true).getBoolean(true);
        Config.DESICHALKOS_HAMMER_ENABLE = /*EL:285*/a1.get("Hammers", "Enable Desichaloks Hammer", true).getBoolean(true);
        Config.MEUTOITE_HAMMER_ENABLE = /*EL:286*/a1.get("Hammers", "Enable Meutoite Hammer", true).getBoolean(true);
        Config.EXIMITE_HAMMER_ENABLE = /*EL:287*/a1.get("Hammers", "Enable Eximite Hammer", true).getBoolean(true);
        Config.MIDASUM_HAMMER_ENABLE = /*EL:288*/a1.get("Hammers", "Enable Midasum Hammer", true).getBoolean(true);
        Config.SANGUINITE_HAMMER_ENABLE = /*EL:289*/a1.get("Hammers", "Enable Sanguinite Hammer", true).getBoolean(true);
        Config.INOLASHITE_HAMMER_ENABLE = /*EL:290*/a1.get("Hammers", "Enable Inolashite Hammer", true).getBoolean(true);
        Config.VULCANITE_HAMMER_ENABLE = /*EL:291*/a1.get("Hammers", "Enable Vulcanite Hammer", true).getBoolean(true);
        Config.LEMURITE_HAMMER_ENABLE = /*EL:292*/a1.get("Hammers", "Enable Lemurite Hammer", true).getBoolean(true);
        Config.AMARDRINE_HAMMER_ENABLE = /*EL:293*/a1.get("Hammers", "Enable Amardine Hammer", true).getBoolean(true);
        Config.CERUCLASE_HAMMER_ENABLE = /*EL:294*/a1.get("Hammers", "Enable Ceruclase Hammer", true).getBoolean(true);
        Config.KALENDRIDE_HAMMER_ENABLE = /*EL:295*/a1.get("Hammers", "Enable Kalendride Hammer", true).getBoolean(true);
        Config.VYROXERS_HAMMER_ENABLE = /*EL:296*/a1.get("Hammers", "Enable Vyroxers Hammer", true).getBoolean(true);
        Config.CARMOT_HAMMER_ENABLE = /*EL:297*/a1.get("Hammers", "Enable Carmot Hammer", true).getBoolean(true);
        Config.TARTARITE_HAMMER_ENABLE = /*EL:298*/a1.get("Hammers", "Enable Tartarite Hammer", true).getBoolean(true);
        Config.ATLARUS_HAMMER_ENABLE = /*EL:299*/a1.get("Hammers", "Enable Atlarus Hammer", true).getBoolean(true);
        Config.ASTRAL_HAMMER_ENABLE = /*EL:300*/a1.get("Hammers", "Enable Astral Hammer", true).getBoolean(true);
        Config.CELENEGIL_HAMMER_ENABLE = /*EL:301*/a1.get("Hammers", "Enable Celenegil Hammer", true).getBoolean(true);
        Config.AREDRITE_HAMMER_ENABLE = /*EL:302*/a1.get("Hammers", "Enable Arederite Hammer", true).getBoolean(true);
        Config.ORICALCUM_HAMMER_ENABLE = /*EL:303*/a1.get("Hammers", "Enable Oricalcum Hammer", true).getBoolean(true);
        Config.SAPPHIRE_HAMMER_ENABLE = /*EL:304*/a1.get("Hammers", "Enable Saphirre Hammer", true).getBoolean(true);
        Config.MANYULLYN_HAMMER_ENABLE = /*EL:305*/a1.get("Hammers", "Enable Manyullyn Hammer", true).getBoolean(true);
        Config.TOASTER_HAMMER_ENABLE = /*EL:309*/a1.get("Hammers", "Enable Toaster Hammer", true).getBoolean(true);
        Config.CRYOBBY_HAMMER_ENABLE = /*EL:310*/a1.get("Hammers", "Enable Crying Obisidan Hammer", true).getBoolean(true);
        Config.TDM_HAMMER_ENABLE = /*EL:314*/a1.get("Hammers", "Enable DanTDM Hammer", true).getBoolean(true);
        Config.PAT_HAMMER_ENABLE = /*EL:315*/a1.get("Hammers", "Enable FuriousDestroyer Hammer", true).getBoolean(true);
        Config.JEN_HAMMER_ENABLE = /*EL:316*/a1.get("Hammers", "Enable SuperGirlyGamer Hammer", true).getBoolean(true);
        Config.JSQ_HAMMER_ENABLE = /*EL:317*/a1.get("Hammers", "Enable xJSQ Hammer", true).getBoolean(true);
        Config.SKYRS_HAMMER_ENABLE = /*EL:318*/a1.get("Hammers", "Enable SkyTheKidRS Hammer", true).getBoolean(true);
        Config.MRGREGOR_HAMMER_ENABLE = /*EL:319*/a1.get("Hammers", "Enable _MrGregor_ Hammer", true).getBoolean(true);
        Config.THACKATTACK_HAMMER_ENABLE = /*EL:320*/a1.get("Hammers", "Enable ThackAttack_MC Hammer", true).getBoolean(true);
        Config.DEEJAYAXEL_HAMMER_ENABLE = /*EL:324*/a1.get("Hammers", "Enable DeeAxelJay Hammer", true).getBoolean(true);
        Config.RAINBOW_HAMMER_ENABLE = /*EL:328*/a1.get("Hammers", "Enable Rainbow Hammer", true).getBoolean(true);
        Config.MISSING_TEXTURE_HAMMER_ENABLE = /*EL:329*/a1.get("Hammers", "Enable Missing Texture Hammer", true).getBoolean(true);
        /*SL:333*/a1.addCustomCategoryComment("Custom Hammers", "Custom Hammer Settings");
        /*SL:334*/a1.addCustomCategoryComment("Settings", "Settings");
    }
}
